name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  ci:
    name: CI
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Set CI status
        id: ci-status
        run: echo "success=true" >> $GITHUB_OUTPUT